build-dev-back:
  extends:
    - .build
    - .for_dev
  variables:
    BUILD_TARGET: back
    CI_COMMIT_TAG: ${CI_COMMIT_SHORT_SHA}

build-dev-front:
  extends:
    - .build
    - .for_dev
  variables:
    BUILD_TARGET: front
    BUILD_ARGS: "--build-arg=VITE_API_URL=https://iquest-dev.tomsk-it.ru/api"
    CI_COMMIT_TAG: ${CI_COMMIT_SHORT_SHA}

build-prod-back:
  extends:
    - .build
    - .for_prod
  variables:
    BUILD_TARGET: back

build-prod-front:
  extends:
    - .build
    - .for_prod
  variables:
    BUILD_TARGET: front
    BUILD_ARGS: "--build-arg=VITE_API_URL=https://iq.tomsk.ru/api"
